name: Gradle Check (Jenkins) Test
on: pull_request

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment variables (Push)
        if: github.event_name == 'push'
        run: |
            repo_url="https://github.com/opensearch-project/OpenSearch"
            ref_id=$(git rev-parse HEAD)
            branch_name=$(git rev-parse --abbrev-ref HEAD)
            echo "pr_from_sha=$ref_id" >> $GITHUB_ENV
            echo "pr_from_clone_url=$repo_url" >> $GITHUB_ENV
            echo "pr_to_clone_url=$repo_url" >> $GITHUB_ENV
            echo "pr_title=Push trigger $branch_name $ref_id $repo_url" >> $GITHUB_ENV
            echo "pr_number=Null" >> $GITHUB_ENV

      - name: Setup Result Status
        if: always()
        run: |
            WORKFLOW_URL=https://build.ci.opensearch.org/job/gradle-check/6939/
            RESULT=FAILURE
            echo "workflow_url=$WORKFLOW_URL" >> $GITHUB_ENV
            echo "result=$RESULT" >> $GITHUB_ENV

      - name: Extract Test Failure
        if: ${{ github.event_name == 'pull_request' }}
        run: |
            TEST_FAILURES=`curl -s "${{ env.workflow_url }}/testReport/api/json?tree=suites\[cases\[status,className,name\]\]" | jq -r '.. | objects | select(.status=="FAILED",.status=="REGRESSION") | (.className + "." +  .name)' | uniq -c | sort -n -r | head -n 10`
            if [[ "$TEST_FAILURES" != "" ]]
            then
              echo "test_failures<<EOF" >> $GITHUB_ENV
              echo "" >> $GITHUB_ENV
              echo "* **FAILURES:**" >> $GITHUB_ENV
              echo '```' >> $GITHUB_ENV
              echo "$TEST_FAILURES" >> $GITHUB_ENV
              echo '```' >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            fi

      - name: Create Comment Failure
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 113
          body: |
              ### Gradle Check (Jenkins) Run Completed with:
              * **RESULT:** ${{ env.result }} :x: ${{ env.test_failures }}
              * **URL:** ${{ env.workflow_url }}
              * **CommitID:** ${{ env.pr_from_sha }}
              Please examine the workflow log, locate, and copy-paste the failure below, then iterate to green.
              Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
